{
 "title": "TechChallege 2 - Prometheus - API Metrics",
 "tags": [
  "prometheus-net",
  "net",
  "prometheus",
  ".net",
  ".net core"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instances",
    "label": "instances",
    "query": "label_values(http_requests_received_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Data e Hora de Início do Serviço",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance =~ \"$instances\"} * 1000"
    }
   ]
  },
  {
   "title": "Status do Serviço",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"techChallenge2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência por Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, endpoint) (rate(http_request_duration_seconds_bucket[1h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Contagem de Requisições x Status de Respostas",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(code) (increase(http_requests_received_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "The duration of HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(le) (increase(http_request_duration_seconds_bucket[$__interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Total number of threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "process_num_threads", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Uso da CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "system_runtime_cpu_usage * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de Memória",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (dotnet_total_memory_bytes /1024/1024)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Process working set",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_working_set_bytes /1024/1024",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}